### ISSUE TITLE
Popisy úloh

### ISSUE THREAD

**Issue by abecedoid** [optagon/letecke_psychotesty#2]
Tady nějaké připomínky k těm popisům úloh:

1. Sensomotorní funkce - ta obtížnost se s časem nezvyšuje, jak je psáno. Mám to tak udělat, aby to bylo čím dal těžší? Myslel jsem, že cílem je ukázat, že se ti nezhoršuje ta průměrná odchylka - tedy, že výkon máš pořád stejnej.
2. Obíhací kolečko - opravit typo *kontrasní*
3.

**Comment by optagon** [comment]
1. u pizzy by to myslim rikat nemelo. Rika to u multitaskingu, ale ten predelam celej, ten je vic nez na picu
2. opraveno
