### ISSUE TITLE
zmenit datovy model

### ISSUE THREAD

**Issue by optagon** [optagon/letecke_psychotesty#22]
potrebujeme minimalne platnost od, platnost do

**Comment by abecedoid** [comment]
koukam ted tam mame jen username a hash hesla, tak navrhuju k tomu navic 

* datum registrace
* zacatek platnosti 
* konec platnosti
* email
* active_session - to je na limitaci concurrent loginů, aby mohl byt jeden user jen jednou prihlasenej - viz limit concurrent logins issue

**Comment by optagon** [comment]
jojo, datum registrace a konce urcite , ale email bude problem. Myslel jsem ze vygenerujeme nekolik random jmen a hesel a to jim pak posleme. udrzovat loginy a emailu to zatim muzeme treba v nejakym excelu. To active_session ale asi nemuzeme drzet v databazi, abysme meli pri kazdym prihlaseni novej radek
