### ISSUE TITLE
Pizza  - parbička se zobrazuje hrozně malá

### ISSUE THREAD

**Issue by abecedoid** [optagon/letecke_psychotesty#5]
Make pařba bigger
Aspon je to hrozně maly na mym pravekym 1600 x 900 displeji

**Comment by optagon** [comment]
jo , jako mohlo by to byt vetsi, ale asi na tom business uplne nestoji :D

**Comment by abecedoid** [comment]
jo to asi ne, ale já naprosto netušim proč to tak je, tak to asi na chvíli odložim:D ty html a css, to je moje peklo
